In [1]:
import torch
from torch.nn import functional as F

In [2]:
# 初始化向量
x1 = torch.randn(1, 3, 4)
x2 = torch.randn(1, 5, 4)

In [3]:
# 计算相似度得分
similarity_score = torch.matmul(x1, x2.transpose(1, 2))
print('similarity_score:\n', similarity_score)

similarity_score:
 tensor([[[ 1.3041, -1.2298,  1.0772, -1.4588, -0.6118],
         [ 3.2634, -4.0418,  7.1824, -2.5894, -4.6967],
         [-0.8591,  0.9973, -5.0011, -1.3004,  4.4062]]])


In [ ]:
# 注意力权重
attn_weight = F.softmax(similarity_score, dim=2)
print('attn_weight:\n', attn_weight)

attn_weight:
 tensor([[[4.7923e-01, 3.8029e-02, 3.8195e-01, 3.0244e-02, 7.0548e-02],
         [1.9472e-02, 1.3085e-05, 9.8045e-01, 5.5919e-05, 6.7978e-06],
         [4.9612e-03, 3.1755e-02, 7.8840e-05, 3.1911e-03, 9.6001e-01]]])


In [5]:
# 计算注意力输出
attn_output = torch.matmul(attn_weight, x2)
print('attn_output:\n', attn_output)

attn_output:
 tensor([[[ 0.7047,  0.5608, -0.0482,  0.1224],
         [ 1.4112,  0.6935, -0.7575,  0.6335],
         [-0.6369, -1.3096,  0.8181,  0.6053]]])
