In [1]:
import torch
from torch.nn import functional as F

In [2]:
Q = torch.randn(1, 3, 4)
K = torch.randn(1, 4, 4)
V = torch.randn(1, 4, 4)

In [3]:
# 相似度得分
similarity_score = torch.matmul(Q, K.transpose(-2, -1))
print('similarity_score:\n', similarity_score)

similarity_score:
 tensor([[[-0.9860, -4.0286, -2.6361,  0.6337],
         [-2.7886, -3.4204, -1.7496, -0.7183],
         [ 1.4888,  4.4936,  3.4347, -0.4829]]])


In [4]:
# 缩放
scale_factor = similarity_score.size(-1) ** 0.5
print('scale_factor:\n', scale_factor)
scale_weight = similarity_score / scale_factor
print('scale_weight:\n', scale_weight)

scale_factor:
 2.0
scale_weight:
 tensor([[[-0.4930, -2.0143, -1.3181,  0.3168],
         [-1.3943, -1.7102, -0.8748, -0.3591],
         [ 0.7444,  2.2468,  1.7174, -0.2414]]])


In [5]:
# 注意力权重
attn_weight = F.softmax(scale_weight, dim=-1)
print('attn_weight:\n', attn_weight)

attn_weight:
 tensor([[[0.2561, 0.0559, 0.1122, 0.5757],
         [0.1606, 0.1171, 0.2700, 0.4522],
         [0.1175, 0.5278, 0.3109, 0.0438]]])


In [6]:
# 注意力输出
attn_output = torch.matmul(attn_weight, V)
print('attn_output:\n', attn_output)

attn_output:
 tensor([[[ 0.8463,  0.1910, -0.7612,  0.4463],
         [ 0.8737,  0.0964, -0.6657,  0.3455],
         [ 0.5151, -0.0806, -0.6415, -0.1069]]])
