In [1]:
import torch
from torch.nn import functional as F

In [2]:
# 初始化向量
x1 = torch.randn(1, 3, 4)
x2 = torch.randn(1, 5, 4)

In [3]:
# 计算相似度得分
similarity_score = torch.matmul(x1, x2.transpose(1, 2))
print('similarity_score:\n', similarity_score)

similarity_score:
 tensor([[[-0.0093, -0.4817, -1.2433, -0.3959, -0.6269],
         [ 0.1143,  2.2590,  4.2237,  2.6393,  0.2414],
         [-1.0587,  2.0005,  4.5182,  3.0956,  1.4810]]])


In [4]:
# 缩放
缩放因子 = x1.size(-1) ** 0.5
缩放权重 = similarity_score / 缩放因子

In [5]:
# 注意力权重
attn_weight = F.softmax(缩放权重, dim=2)
print('attn_weight:\n', attn_weight)

attn_weight:
 tensor([[[0.2572, 0.2031, 0.1388, 0.2120, 0.1889],
         [0.0612, 0.1790, 0.4780, 0.2165, 0.0653],
         [0.0299, 0.1382, 0.4865, 0.2389, 0.1066]]])


In [6]:
# 计算注意力输出
attn_output = torch.matmul(attn_weight, x2)
print('attn_output:\n', attn_output)

attn_output:
 tensor([[[ 0.2706,  0.7339,  0.2997, -0.1098],
         [ 0.2968,  1.2934,  0.3733, -0.3443],
         [ 0.2677,  1.2730,  0.4297, -0.3645]]])
