In [7]:
import torch
from torch import nn
from torch.nn import functional as F

In [5]:
x = torch.randn(1, 3, 4)
similarity_score = torch.matmul(x, x.transpose(-2, -1))
print('similarity_score:\n', similarity_score)
scale_factor = similarity_score.size(-1) ** 0.5
print('scale_factor:\n', scale_factor)
scale_weight = similarity_score / scale_factor
print('scale_weight:\n', scale_weight)
attn_weight = F.softmax(scale_weight, dim=-1)
print('attn_weight:\n', attn_weight)
attn_output = torch.matmul(similarity_score, x)
print('attn_output:\n', attn_output)

similarity_score:
 tensor([[[ 3.5084,  1.3105, -0.1577],
         [ 1.3105,  1.6413,  1.1346],
         [-0.1577,  1.1346,  1.2624]]])
scale_factor:
 1.7320508075688772
scale_weight:
 tensor([[[ 2.0255,  0.7566, -0.0911],
         [ 0.7566,  0.9476,  0.6551],
         [-0.0911,  0.6551,  0.7288]]])
attn_weight:
 tensor([[[0.7135, 0.2006, 0.0859],
         [0.3211, 0.3887, 0.2901],
         [0.1859, 0.3920, 0.4221]]])
attn_output:
 tensor([[[-0.0300, -3.4212,  4.6600,  4.9364],
         [-1.2434,  0.0689,  2.8418,  3.4408],
         [-1.2856,  1.5648,  0.9370,  1.4410]]])


In [8]:
x = torch.randn(1, 3, 4)

linear_q = nn.Linear(4, 4)
linear_k = nn.Linear(4, 4)
linear_v = nn.Linear(4, 4)

Q = linear_q(x)
K = linear_k(x)
V = linear_v(x)

similarity_score = torch.matmul(Q, K.transpose(-2, -1))
print('similarity_score:\n', similarity_score)
scale_factor = similarity_score.size(-1) ** 0.5
print('scale_factor:\n', scale_factor)
scale_weight = similarity_score / scale_factor
print('scale_weight:\n', scale_weight)
attn_weight = F.softmax(scale_weight, dim=-1)
print('attn_weight:\n', attn_weight)
attn_output = torch.matmul(similarity_score, V)
print('attn_output:\n', attn_output)

similarity_score:
 tensor([[[-0.2914, -1.6899, -2.9672],
         [ 1.0930,  1.2264, -1.1606],
         [ 1.0243,  1.2084,  0.7361]]], grad_fn=<UnsafeViewBackward0>)
scale_factor:
 1.7320508075688772
scale_weight:
 tensor([[[-0.1682, -0.9757, -1.7131],
         [ 0.6311,  0.7081, -0.6701],
         [ 0.5914,  0.6977,  0.4250]]], grad_fn=<DivBackward0>)
attn_weight:
 tensor([[[0.6027, 0.2688, 0.1286],
         [0.4251, 0.4592, 0.1157],
         [0.3380, 0.3759, 0.2862]]], grad_fn=<SoftmaxBackward0>)
attn_output:
 tensor([[[-8.6620,  2.5163, -0.4450,  1.2735],
         [-2.0277, -0.3835, -3.0741, -2.9376],
         [ 2.7943, -1.3640, -1.6057, -2.1431]]], grad_fn=<UnsafeViewBackward0>)
